const dashboardData = {
    currency: "$",
    social_activity: [
      {
        id: 1,
        name: "Kava",
        code: "KAVA",
        interactions: 64,
        variation: "+255.56",
        icon: "https://auth0.com",
      },
      {
        id: 2,
        name: "Cardano",
        code: "ADA",
        interactions: "5.06K",
        variation: "+49.28",
        icon: "https://bsky.app.com",
      },
      {
        id: 3,
        name: "Trust Wallet Token",
        code: "TWT",
        interactions: "26.38K",
        variation: "+13.78",
        icon: "https://dribbble.com",
      },
      {
        id: 4,
        name: "Etherum Classic",
        code: "ETC",
        interactions: "256",
        variation: "+10.34",
        icon: "https://developer.mozilla.com",
      },
      {
        id: 5,
        name: "Monero",
        code: "XMR",
        interactions: "1.9K",
        variation: "+9.87",
        icon: "https://gitlab.com",
      },
    ],
    volume: [
      {
        id: 1,
        name: "Binance",
        code: "",
        volume: "11.82B",
        variation: "-4.87",
        icon: "https://ravelry.com",
      },
      {
        id: 2,
        name: "Gate.io",
        code: "",
        volume: "976.92",
        variation: "-3.44%",
        icon: "https://mastodon.com",
      },
      {
        id: 3,
        name: "Coinbase Exchange",
        code: "",
        volume: "1.46B",
        variation: "-9.09",
        icon: "https://medium.com",
      },
      {
        id: 4,
        name: "LBank",
        code: "",
        volume: "1.46B",
        variation: "+13.11",
        icon: "https://pixiv.com",
      },
      {
        id: 5,
        name: "MEXC Global",
        code: "",
        volume: "946.82M",
        variation: "-12.53",
        icon: "https://squarespace.com",
      },
    ],
    gainers: [
      {
        id: 1,
        name: "ADAUP",
        code: "ADAUP",
        gain: "0.503",
        variation: "+22.83",
        icon: "https://rdio.com",
      },
      {
        id: 2,
        name: "Injective",
        code: "INJ",
        gain: "8.98",
        variation: "+22.13%",
        icon: "https://meetup.com",
      },
      {
        id: 3,
        name: "Band Protocol",
        code: "BAND",
        gain: "1.726",
        variation: "+20.73",
        icon: "https://soundcloud.com",
      },
      {
        id: 4,
        name: "COTI",
        code: "COTI",
        gain: "0.0801",
        variation: "+17.84",
        icon: "https://twitch.com",
      },
      {
        id: 5,
        name: "Conflux",
        code: "CFX",
        gain: "0.321",
        variation: "+15.35",
        icon: "https://stackoverflow.com",
      },
    ],
    losers: [
      {
        id: 1,
        name: "ARPA Chain",
        code: "ARPA",
        lose: "0.05045",
        variation: "-9.06",
        icon: "https://threads.com",
      },
      {
        id: 2,
        name: "Klaytn",
        code: "KLAY",
        lose: "0.1730",
        variation: "-6.49%",
        icon: "https://patreon.com",
      },
      {
        id: 3,
        name: "Ethernity Chain",
        code: "ERN",
        lose: "1.853",
        variation: "-5.12",
        icon: "https://yandex.com",
      },
      {
        id: 4,
        name: "FC Porto Fan Token",
        code: "PORTO",
        lose: "2.3739",
        variation: "-1.98",
        icon: "https://upwork.com",
      },
      {
        id: 5,
        name: "Orion Protocol",
        code: "ORN",
        lose: "1.0530",
        variation: "-1.89%",
        icon: "https://x.com",
      },
    ],
  };
  
  export default dashboardData;